#! /bin/sh
heroku pg:backups:capture \
&& heroku pg:backups:download \
&& pg_restore --verbose --clean --no-acl --no-owner -h localhost -U oliver -d teamexchange latest.dump \
; rm latest.dump; python manage.py change_all_passwords
