# Generated by Django 2.0.5 on 2018-06-11 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, help_text='Date and                                             Time of price', verbose_name='Closing Price Date')),
                ('price', models.IntegerField(help_text='Price', verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_fixture', models.DateTimeField(help_text='Date and Time for fixture', verbose_name='Date and Time')),
                ('round', models.CharField(choices=[('gp', 'Group Stage'), ('ko', 'Knock Out')], max_length=2)),
                ('team_1_goals', models.IntegerField(blank=True, help_text='Number of goals Team 1 scored', null=True, verbose_name='Team 1 goals')),
                ('team_2_goals', models.IntegerField(blank=True, help_text='Number of goals Team 2 scored', null=True, verbose_name='Team 2 goals')),
                ('winner', models.CharField(blank=True, choices=[('draw', 'Draw'), (None, 'Null')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalInvestments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, help_text='Date and                                             Time of transaction', verbose_name='Transaction Date')),
                ('total_value_of_investments', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField(choices=[(-1, 'Sell'), (1, 'Buy')], help_text='Show whether transaction                                           was a buy or sell', verbose_name='Transaction Type')),
                ('number_shares', models.IntegerField(help_text='Number of shares bought or                                         sold in this transaction', verbose_name='Number of Shares')),
                ('price', models.DecimalField(decimal_places=2, help_text='Current Price of the team', max_digits=5, verbose_name='Current Price')),
                ('transaction_date', models.DateTimeField(auto_now=True, help_text='Date and                                             Time of transaction', verbose_name='Transaction Date')),
                ('transaction_mode', models.IntegerField(choices=[(-1, 'User Generated'), (1, 'Automatically Generated')])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invested', models.DecimalField(decimal_places=8, default=0, max_digits=50)),
                ('cash_avaliable', models.DecimalField(decimal_places=8, default=0, max_digits=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_code', models.CharField(help_text='Team Code', max_length=3, primary_key=True, serialize=False, verbose_name='Team Code')),
                ('image', models.CharField(blank=True, help_text='Location of flag image', max_length=200, verbose_name='Image Location')),
                ('number_of_shares_held', models.IntegerField(help_text='Number of shares held', verbose_name='Number shares held')),
                ('eliminated', models.BooleanField(default=False, help_text='Has team been                                      eliminated')),
                ('current_price', models.DecimalField(decimal_places=8, help_text='Current Price of the team', max_digits=50, null=True, verbose_name='Current Price')),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='team_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teamapp.Team'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Profile'),
        ),
        migrations.AddField(
            model_name='historicalinvestments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Profile'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_team1', to='teamapp.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_team2', to='teamapp.Team'),
        ),
        migrations.AddField(
            model_name='closingvalue',
            name='team_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teamapp.Team'),
        ),
    ]
