# Generated by Django 2.0.5 on 2018-06-13 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingvalue',
            name='team_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_team1', to='teamapp.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_team2', to='teamapp.Team'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='team_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Team'),
        ),
    ]
