# Generated by Django 2.0.5 on 2018-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_auto_20180613_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='winner',
            field=models.CharField(blank=True, choices=[('URU', 'URU'), ('TUN', 'TUN'), ('SUI', 'SUI'), ('SWE', 'SWE'), ('ESP', 'ESP'), ('ARG', 'ARG'), ('AUS', 'AUS'), ('BEL', 'BEL'), ('BRA', 'BRA'), ('COL', 'COL'), ('CRC', 'CRC'), ('CRO', 'CRO'), ('DEN', 'DEN'), ('ENG', 'ENG'), ('FRA', 'FRA'), ('GER', 'GER'), ('ISL', 'ISL'), ('IRN', 'IRN'), ('JPN', 'JPN'), ('KOR', 'KOR'), ('MEX', 'MEX'), ('MAR', 'MAR'), ('NGA', 'NGA'), ('PAN', 'PAN'), ('PER', 'PER'), ('POL', 'POL'), ('POR', 'POR'), ('SEN', 'SEN'), ('SRB', 'SRB'), ('RUS', 'RUS'), ('KSA', 'KSA'), ('EGY', 'EGY'), ('draw', 'Draw'), (None, 'Null')], max_length=4, null=True),
        ),
    ]
