# Generated by Django 2.0.5 on 2018-05-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0002_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, help_text='Date and                                             Time of price', verbose_name='Closing Price Date')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_code', models.CharField(help_text='Team Code', max_length=3, primary_key=True, serialize=False, verbose_name='Team Code')),
                ('image', models.CharField(help_text='Location of flag image', max_length=100, verbose_name='Image Location')),
                ('number_of_shares_held', models.IntegerField(help_text='Number of shares held', verbose_name='Number shares held')),
                ('eliminated', models.BooleanField(default=False, help_text='Has team been                                      eliminated')),
            ],
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamapp_fixtures_related1', to='teamapp.Teams'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamapp_fixtures_related2', to='teamapp.Teams'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='winner',
            field=models.CharField(choices=[(models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamapp_fixtures_related1', to='teamapp.Teams'), 'Team 1'), (models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamapp_fixtures_related2', to='teamapp.Teams'), 'Team 2'), ('draw', 'Draw')], max_length=4, null=True),
        ),
    ]
