# Generated by Django 2.0.5 on 2018-06-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0003_auto_20180613_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='stadium',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
