# Generated by Django 2.0.5 on 2018-05-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0003_auto_20180528_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingvalue',
            name='price',
            field=models.IntegerField(default=0, help_text='Price', verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closingvalue',
            name='team_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='teamapp.Teams'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investments',
            name='closing_price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='teamapp.ClosingValue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investments',
            name='team_code',
            field=models.ForeignKey(default='ENG', on_delete=django.db.models.deletion.DO_NOTHING, to='teamapp.Teams'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='current_price',
            field=models.IntegerField(default=0, help_text='Current Price of the team', verbose_name='Current Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixtures_team1', to='teamapp.Teams'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixtures_team2', to='teamapp.Teams'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='winner',
            field=models.CharField(choices=[(models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixtures_team1', to='teamapp.Teams'), 'Team 1'), (models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixtures_team2', to='teamapp.Teams'), 'Team 2'), ('draw', 'Draw')], max_length=4, null=True),
        ),
    ]
