# Generated by Django 2.0.5 on 2018-05-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('teamapp', '0004_auto_20180528_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_fixture', models.DateTimeField(help_text='Date and Time for fixture', verbose_name='Date and Time')),
                ('round', models.CharField(choices=[('gp', 'Group Stage'), ('ko', 'Knock Out')], max_length=2)),
                ('team_1_goals', models.IntegerField(help_text='Number of goals Team 1 scored', verbose_name='Team 1 goals')),
                ('team_2_goals', models.IntegerField(help_text='Number of goals Team 2 scored', verbose_name='Team 2 goals')),
                ('winner', models.CharField(choices=[(models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_team1', to='teamapp.Team'), 'Team 1'), (models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_team2', to='teamapp.Team'), 'Team 2'), ('draw', 'Draw')], max_length=4, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Investments',
            new_name='Investment',
        ),
        migrations.RemoveField(
            model_name='fixtures',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='fixtures',
            name='team_2',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
        migrations.DeleteModel(
            name='Fixtures',
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_team1', to='teamapp.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_team2', to='teamapp.Team'),
        ),
    ]
