# Generated by Django 2.0.5 on 2018-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0004_fixture_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='stadium',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
