# Generated by Django 2.0.5 on 2018-06-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0005_auto_20180614_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestments',
            name='total_cash_avaliable',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='winner',
            field=models.CharField(blank=True, choices=[('SWE', 'SWE'), ('GER', 'GER'), ('BRA', 'BRA'), ('SRB', 'SRB'), ('SUI', 'SUI'), ('KOR', 'KOR'), ('ARG', 'ARG'), ('ISL', 'ISL'), ('KSA', 'KSA'), ('COL', 'COL'), ('NGA', 'NGA'), ('URU', 'URU'), ('PAN', 'PAN'), ('MAR', 'MAR'), ('RUS', 'RUS'), ('CRO', 'CRO'), ('BEL', 'BEL'), ('AUS', 'AUS'), ('EGY', 'EGY'), ('SEN', 'SEN'), ('TUN', 'TUN'), ('CRC', 'CRC'), ('JPN', 'JPN'), ('PER', 'PER'), ('ESP', 'ESP'), ('MEX', 'MEX'), ('ENG', 'ENG'), ('POR', 'POR'), ('IRN', 'IRN'), ('POL', 'POL'), ('DEN', 'DEN'), ('FRA', 'FRA'), ('draw', 'Draw'), (None, 'Null')], max_length=4, null=True),
        ),
    ]
