# Generated by Django 2.0.5 on 2018-05-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0005_auto_20180528_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.CharField(blank=True, help_text='Location of flag image', max_length=100, verbose_name='Image Location'),
        ),
    ]
