# Generated by Django 2.0.5 on 2018-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0006_auto_20180528_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='closing_price',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investmentID',
        ),
        migrations.AddField(
            model_name='investment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
