# Generated by Django 2.0.5 on 2018-06-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0006_auto_20180617_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalInvestments',
            new_name='HistoricalInvestment',
        ),
    ]
