# Generated by Django 2.0.5 on 2018-05-29 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0007_auto_20180529_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='team_1_goals',
            field=models.IntegerField(blank=True, help_text='Number of goals Team 1 scored', null=True, verbose_name='Team 1 goals'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team_2_goals',
            field=models.IntegerField(blank=True, help_text='Number of goals Team 2 scored', null=True, verbose_name='Team 2 goals'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='winner',
            field=models.CharField(blank=True, choices=[(models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_team1', to='teamapp.Team'), 'Team 1'), (models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_team2', to='teamapp.Team'), 'Team 2'), ('draw', 'Draw'), (None, 'Null')], default=0, max_length=4),
            preserve_default=False,
        ),
    ]
