# Generated by Django 2.0.5 on 2018-05-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0008_auto_20180529_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='winner',
            field=models.CharField(blank=True, choices=[(models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_team1', to='teamapp.Team'), 'Team 1'), (models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fixture_team2', to='teamapp.Team'), 'Team 2'), ('draw', 'Draw'), (None, 'Null')], max_length=4, null=True),
        ),
    ]
