# Generated by Django 2.0.5 on 2018-06-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0009_auto_20180617_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvestment',
            name='datetime',
            field=models.DateField(help_text='Date and                                             Time of transaction', verbose_name='Transaction Date'),
        ),
    ]
