# Generated by Django 2.0.5 on 2018-05-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0009_auto_20180529_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='winner',
            field=models.CharField(blank=True, choices=[(1, 'Team 1'), (2, 'Team 2'), ('draw', 'Draw'), (None, 'Null')], max_length=4, null=True),
        ),
    ]
