# Generated by Django 2.0.5 on 2018-05-31 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0010_auto_20180530_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='id',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='winner',
            field=models.CharField(blank=True, choices=[('1', 'Team 1'), ('2', 'Team 2'), ('draw', 'Draw'), (None, 'Null')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='team_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='teamapp.Team'),
        ),
    ]
