# Generated by Django 2.0.5 on 2018-06-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0010_auto_20180617_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='winner',
            field=models.CharField(blank=True, choices=[('draw', 'Draw'), (None, 'Null')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinvestment',
            name='datetime',
            field=models.DateField(auto_now=True, help_text='Date and                                             Time of transaction', verbose_name='Transaction Date'),
        ),
    ]
