# Generated by Django 2.0.5 on 2018-05-31 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0011_auto_20180531_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='team_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teamapp.Team'),
        ),
    ]
