# Generated by Django 2.0.5 on 2018-05-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0013_auto_20180531_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cash_avaliable',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
