# Generated by Django 2.0.5 on 2018-06-03 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0014_auto_20180531_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvestments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, help_text='Date and                                             Time of transaction', verbose_name='Transaction Date')),
                ('total_value_of_investments', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fixture',
            name='winner',
            field=models.CharField(blank=True, choices=[('ENG', 'ENG'), ('GER', 'GER'), ('MOR', 'MOR'), ('POR', 'POR'), ('draw', 'Draw'), (None, 'Null')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cash_avaliable',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
        migrations.AddField(
            model_name='historicalinvestments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teamapp.Profile'),
        ),
    ]
