# Generated by Django 2.0.5 on 2018-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0015_auto_20180603_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Current Price of the team', max_digits=5, null=True, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cash_avaliable',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_price',
            field=models.DecimalField(decimal_places=2, help_text='Current Price of the team', max_digits=5, null=True, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.CharField(blank=True, help_text='Location of flag image', max_length=200, verbose_name='Image Location'),
        ),
    ]
