# Generated by Django 2.0.5 on 2018-06-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0016_auto_20180609_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Current Price of the team', max_digits=5, verbose_name='Current Price'),
            preserve_default=False,
        ),
    ]
