# Generated by Django 2.0.5 on 2018-06-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0017_auto_20180609_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='transaction_mode',
        ),
    ]
