# Generated by Django 2.0.5 on 2018-06-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0018_remove_investment_transaction_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='transaction_mode',
            field=models.IntegerField(choices=[(-1, 'User Generated'), (1, 'Automatically Generated')], default=-1),
            preserve_default=False,
        ),
    ]
