# Generated by Django 2.0.5 on 2018-06-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0019_investment_transaction_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
