# Generated by Django 2.0.5 on 2018-06-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0020_auto_20180610_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
