# Generated by Django 2.0.5 on 2018-06-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0021_auto_20180610_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvestments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Profile'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cash_avaliable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
